### ISSUE TITLE
More

### ISSUE THREAD

**Issue by sidanuk** [mikethedj4/Polyrise#2]
This is brilliant , bring it back to life with he ability to import user blocks

**Comment by michaelsboost** [comment]
Thanks I'm pleased to hear you're enjoying Polyrise 👍 

How Polyrise handles adding blocks is through a parent > child relationship.

You see `<div data-filter="header">` is what holds all of the blocks the user will add...

```
<div class="addblock">
  <img src="blocks/header1.png">
  <textarea class="hide" data-block="code">
    <div class="polyriseblock notgrid">
      <!-- polyrise block code -->
    </div>
  </textarea>
</div>
```

The above is a simple example of how you can easily add a block into the app. This can be saved in the index.html. There's no current implemented work around to this and I've abandoned continuing development on this project in favor of other projects. (Hence why it's been discontinued since October 19, 2019)
